### ISSUE TITLE
Can't change business branch

### ISSUE THREAD

**Issue by JollyTheDuck** [nnichael/MOGL#100]
**List your installed mods**

- optifine
- fabric

**How you triggered the behavior**

- Have Prop a part of a branch
- go to add prop to a different branch
- can't change branch

**What you expected would happen**

- have the prop change braches

**What actually happened**

- I was told it was already linked to a branch

**Logs and screenshots**
- Please attach or link to complete log(s). Even if the log doesn't _seem_ to be relevant, it often may.
- Screenshots are also very helpful for illustrating visual defects.

**Comment by PigleB605** [comment]
Thanks for the report! It turns out that properties were saving their linked branch, but branches weren't saving their list of properties. This has been fixed now. 

If you have any more issues, please make a new report!
