### ISSUE TITLE
Missing texture on plant 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#107]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- water my plant (I believe it was tobacco plant) 
- It grows but doesn’t have a texture & It wasnt overwatered. 

![9BE4D881-CB25-4864-A82A-CD72F299EEDD](https://user-images.githubusercontent.com/91354495/172931016-ac76af45-8705-40a9-8dfc-6764c81de1bd.jpeg)

**Comment by nnichael** [comment]
Will be fixed on release!
