### ISSUE TITLE
You can mine any dead coral anywhere with a nugget pickaxe

### ISSUE THREAD

**Issue by AceTheGayest** [nnichael/MOGL#110]
**List your installed mods**

- optifine

**How you triggered the behavior**

-log into mogl
-go to jail
-get nugget brand pickaxe
-get out of jail
-jump into the guard path area to see if i can mine the dead coral
-im able to mine the dead coral and its still gone even if i relog

**What you expected would happen**

- kinda expected it to dissapear ngl

**What actually happened**

- was able to mine it
![Uploading image_2022-06-09_173034327.png…]()

**Logs and screenshots**
- Please attach or link to complete log(s). Even if the log doesn't _seem_ to be relevant, it often may.
- Screenshots are also very helpful for illustrating visual defects.

**Comment by AceTheGayest** [comment]
edit: you can only mine it in some areas. idk why

**Comment by nnichael** [comment]
Thanks! Will close this for now, since it's a builder issue. Will go on later and replace the pathway blocks.
