### ISSUE TITLE
Running level does not go down

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#119]
**List your installed mods**

- none

**How you triggered the behavior**

- log into MOGL
- run for a minute straight

**What you expected would happen**

- running level to go down

**What actually happened**

- running level occasionally goes down by 1 but quickly goes back to full levels while running

**Comment by nnichael** [comment]
Did you have any ailments or Boosters active? Did you have a fire going? Both of these will increase your energy.

**Comment by Pumpkin-Headington** [comment]
oh yes it was the arson buff. never mind then
