### ISSUE TITLE
Lumberjack

### ISSUE THREAD

**Issue by ChillyCyanide** [nnichael/MOGL#128]
**List your installed mods**

- none

**How you triggered the behavior**

- Trying to prestige lumberjack from 69 to 70

**What you expected would happen**

- Prestige

**What actually happened**

- I Was told I need knowledge in atleast 1 of the 3 categories being Geology, Numismatogy, or Physical education. All 3 knowdlege stats are at 7.

**Logs and screenshots**

**Comment by nnichael** [comment]
Your prestige is higher than your knowledge levels for those categories combined.

This means you'll have to max out the levels in all categories to remove the prestige cap.

This only happens to existing players with prestige levels higher than their knowledge. New players won't have this issue.
