### ISSUE TITLE
Mask number not updating

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#131]
**List your installed mods**

- none

**How you triggered the behavior**

- log into MOGL
- wear crime mask
- commit several crimes

**What you expected would happen**

- the "(5)" number on the mask would decrease and show how many uses are left

**What actually happened**

- the number on the mask never lowered but still eventually broke. on rare occasion evidence would drop after committing a crime even though i was still wearing the mask. i do no know yet how to replicate the rare occurrence yet but will keep testing for it.

**Comment by nnichael** [comment]
@Pumpkin-Headington masks do not stop physical evidence from dropping, they stop people from witnessing crimes. The (5) thing seems bugged, tho.
