### ISSUE TITLE
Text above mob control npc head

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#135]
**List your installed mods**

- none

**How you triggered the behavior**

- log into MOGL
- go to mob control building
- look at mob control npc

**What you expected would happen**

- Only the name would appear

**What actually happened**

- The name appeared with random text also above it, it disappears in F1 mode though.

**Logs and screenshots**
<img width="962" alt="Screen Shot 2022-06-14 at 7 25 31 AM" src="https://user-images.githubusercontent.com/92835506/173607254-b57802f2-6990-4ad6-bba7-2b982a8d01dc.png">
<img width="873" alt="Screen Shot 2022-06-14 at 7 25 55 AM" src="https://user-images.githubusercontent.com/92835506/173607289-bf91bcd3-0964-4fc0-b653-4c988479d72d.png">

**Comment by nnichael** [comment]
@Pumpkin-Headington Thanks for the report. This seems to be an issue with a supplementary plugin, we'll just have to wait until they fix it. 🙏
