### ISSUE TITLE
Sharing evidence

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#139]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
-  collect evidence from a player 
- share that evidence with the player who dropped the evidence 
- it lets you share 

reporting this incase it’s a bug since i know players can’t pick up their own evidence

**Comment by nnichael** [comment]
@m0nts3 not a bug! As long as the player can't pick up and dispose of their own physical evidence, we're good. Sharing it does not take it from your personal evidence locker, just spreads the info all around town. Thanks for the report. 🙏
