### ISSUE TITLE
unable to pick up germs

### ISSUE THREAD

**Issue by Eqipped** [nnichael/MOGL#141]
**List your installed mods**

- none

**How you triggered the behavior**

- attempt to pick up germ off the floor

**What you expected would happen**

- get the germ and make syringe

**What actually happened**

- the germ stayed on the floor

**Logs and screenshots**

-none

**Comment by nnichael** [comment]
@Eqipped Players with a low average balance (~$2,000) can not pick up germs. I'll close this for now, feel free to DM me or comment (if possible) if this is not the case, I'll reopen.
