### ISSUE TITLE
Potential criminal database bug? 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#159]
**List your installed mods**
- optifine

**How you triggered the behavior**
- log into MOGL
- check criminal database
- it was empty, but yesterday there were some people who were not afa, on the criminal database…and i’m pretttttyyyy sure you cant lose levels unless you’re afa. don’t know what could’ve caused this though .-.

**Comment by nnichael** [comment]
@m0nts3 I think eventually, if a player is not made AFA fast enough, the evidence does expire. So, this maaay not be a bug. I'll close for now, thanks!
