### ISSUE TITLE
glass and /build mode 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#165]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- place a glass block (i placed stained glass to be specific) 
- break it in the same build mode 
- didn’t drop, & i was expecting it to drop

**Comment by PigleB605** [comment]
Hey, thanks for the report @m0nts3! What tool were you using to break the glass? In Vanilla MC, you can only break it with a silk touch pickaxe, and I don't think MOGL's build mode overrides that.

**Comment by m0nts3** [comment]
> Hey, thanks for the report @m0nts3! What tool were you using to break the glass? In Vanilla MC, you can only break it with a silk touch pickaxe, and I don't think MOGL's build mode overrides that.

Ahhh that makes sense then, i was using my hand ;-;

**Comment by PigleB605** [comment]
> Ahhh that makes sense then, i was using my hand ;-;

Haha no worries; closing this for now, but if you have any more issues, I'll re-open it. Thanks again for checking. :3
