### ISSUE TITLE
Missing property bunnies 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#176]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- some of the properties are missing the property bunny
- missing property bunnies at the seaside mansions 

<img width="1440" alt="5DDC68F7-A6C0-4C2E-87AE-3F6D949E7A85" src="https://user-images.githubusercontent.com/91354495/179674297-3a3b327e-531e-47f7-801b-7c488c2f5df3.png">
<img width="1440" alt="270511F8-D9C0-4BD8-B77E-B0D8578DDCEA" src="https://user-images.githubusercontent.com/91354495/179674313-b2cec0f5-fdab-41b1-9eb8-70bf2588fb00.png">

**Comment by nnichael** [comment]
I'll close this issue for now. This is a citizens2 bug, it's usually fixed on a restart.
