### ISSUE TITLE
Quests bug 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#177]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL (as a new player)
-  do /quests 
- there won’t be any quests to complete, even if you’ve completed the first quest 

![519DD616-F158-4B94-8C5E-40501EDB11C4](https://user-images.githubusercontent.com/91354495/179866812-39d1b9fe-a8d2-4de1-8e68-ea2cbc540974.png)
screenshot from a new player who had problems with the quests

**Comment by nnichael** [comment]
This should be all fixed, for new players, at least. DM if you need me to reset your quests.
