### ISSUE TITLE
Renters can't use sinks in their property

### ISSUE THREAD

**Issue by imshanemitchell** [nnichael/MOGL#180]
**List your installed mods**

Standard MOGL setup!

**How you triggered the behavior**

There is no "sanitation blocks" option for sub-property permissions, so anyone renting a sub-property is unable to use sinks in their room.

**What you expected would happen**

I expected a "sanitation blocks" option for sub-property permissions.

**What actually happened**

There was no "sanitation blocks" option for sub-property permissions.

**Logs and screenshots**
![image](https://user-images.githubusercontent.com/109915021/182462426-35dece8d-2ca6-4556-9532-2c6d37df0b12.png)

**Comment by nnichael** [comment]
I believe this was fixed. Thanks! Re-open if I'm dead wrong :))
