### ISSUE TITLE
Cutting grass outside the city hall is a deathtrap

### ISSUE THREAD

**Issue by Wizard8284** [nnichael/MOGL#181]
**List your installed mods**

- optifine

**How you triggered the behavior**

- Was lawn-mowing outside the city hall like I usually do, and went to the small plots of grass in between the city hall entrance and the big tree

**What you expected would happen**

- Being able to cut grass without dying

**What actually happened**

- Died, as my lawnmower was too close to the edge of the wall, I didn't get off the lawnmower, and i immediately begin suffocating, when I died, I ended up being glitched a whole 3 blocks above where my knocked out body would be, in between the chain and the glass in the window (enidsluv is my witness). Due to some pieces of grass being in the corner and very near the wall under the window, it is difficult to cut grass without getting stuck in the wall. In attempts to recreate the bug/trying to not die, I conclude that even if you don't completely get stuck in the wall, trying to cut the few pieces of grass will result you in taking a few hearts of damage from suffocation. 

**Logs and screenshots**
- Please attach or link to complete log(s). Even if the log doesn't _seem_ to be relevant, it often may.
- Screenshots are also very helpful for illustrating visual defects.
<img width="1512" alt="Screenshot 2022-08-04 at 4 33 19 PM" src="https://user-images.githubusercontent.com/95558729/183327159-2645831d-2b3f-4bbe-bb4f-871d11a9ca62.png">

**Comment by nnichael** [comment]
Will close this for now, since it was with our old vehicle system. Feel free to open this up again if it happens after phillipa 2.0!
