### ISSUE TITLE
(Test Issue) Ya Motha Is Broken

### ISSUE THREAD

**Issue by SleeepyKitten** [nnichael/MOGL#3]
ya motha is VERY broken, pls fix

**Comment by SleeepyKitten** [comment]
^^^^

**Comment by LordTrav** [comment]
Heckin broke af

**Comment by SleeepyKitten** [comment]
![maxresdefault](https://user-images.githubusercontent.com/91351636/134747036-baabc3cd-cf4c-4f80-8453-4e2847ea90f0.jpg)

**Comment by LordTrav** [comment]
![POG Emoji](https://user-images.githubusercontent.com/91351707/134747059-feacf4a2-e637-4d9c-b5fa-406cfd130d86.png)
