### ISSUE TITLE
A spot in my appartment where fps drop

### ISSUE THREAD

**Issue by SkrSkr73** [nnichael/MOGL#36]
There is a very specific spot in my appartment that make the game fps drop for a second everytime I walk there. Two other people confirmed to me that it happens to them too at that same spot.

![2021-10-28_22 51 11](https://user-images.githubusercontent.com/93175014/139365745-82cabdbf-662c-4b4a-85f0-dc2157001879.png)

It is right there in front of the doors.
The address is: Far Jake Arcade

**Comment by nnichael** [comment]
This is more of a Minecraft chunk issue, and cannot not be fixed by MOGL at the moment.
