### ISSUE TITLE
log shop still not set up

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#38]
**list your installed mods**

- none

**how you triggered the behavior**

- log into mogl
- go to log shop in seaside
- right click item frame

**what you expected would happen**

- i would be able to buy the logs

**what actually happened**

- nothing

**logs and screenshots**
<img width="1075" alt="Screen Shot 2021-10-30 at 1 22 30 PM" src="https://user-images.githubusercontent.com/92835506/139557439-65170ad6-6691-4dae-b3ed-90c1e622768d.png">
<img width="677" alt="Screen Shot 2021-10-30 at 1 23 45 PM" src="https://user-images.githubusercontent.com/92835506/139557443-96ccbb90-aff7-4814-aeb9-7f5326cc87b6.png">

**Comment by nnichael** [comment]
Removed the item frames.
