### ISSUE TITLE
meth sold leaderboard broken

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#39]
**list your installed mods**

- none

**how you triggered the behavior**

- log into mogl
- sell meth

**what you expected would happen**

- the meth sold leaderboard would show me at the top.

**what actually happened**

- the /lb leaderboard showed my name but the leaderboard next to the meth villager didn't.

**logs and screenshots**
<img width="570" alt="Screen Shot 2021-10-31 at 11 08 31 AM" src="https://user-images.githubusercontent.com/92835506/139596976-1e54ee1a-d6ff-4f20-8010-32d1e2107313.png">
<img width="372" alt="Screen Shot 2021-10-31 at 11 32 42 AM" src="https://user-images.githubusercontent.com/92835506/139596977-f4f2029d-7cfa-4cdb-9a90-8492e6b53818.png">

**Comment by nnichael** [comment]
It's just slow to update.
