### ISSUE TITLE
medic tracker broken

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#40]
**list your installed mods**

- none

**how you triggered the behavior**

- log into mogl
- see distress call
- click distress call
- distressed player logs out
- different player sends distress call

**what you expected would happen**

- the tracker would show me how far away i was

**what actually happened**

- it said i was already tracking someone
- it was still broken even after relogging

**logs and screenshots**
<img width="671" alt="Screen Shot 2021-10-30 at 11 39 16 PM" src="https://user-images.githubusercontent.com/92835506/139604315-b68f84ce-0155-43d4-8d67-917324e5b822.png">

**Comment by nnichael** [comment]
Can't seem to consistently reproduce. Try to reproduce this consistently.
