### ISSUE TITLE
Name tags don’t work

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#44]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- open a gift box
- win a name tag, use an anvil to name my bird “ben” 
- i right click to apply the name tag to my bird 
- name tag disappears but doesn’t name my bird

**What you expected would happen**

- i expected my birdie to be named ben 

**What actually happened**

- my bird remains without a name and the name tag has disappeared 

**Logs and screenshots**
- will send on discord

**Comment by nnichael** [comment]
Have you tested this on other animals?

**Comment by m0nts3** [comment]
> Have you tested this on other animals?

I have not, i don’t have any more name tags😔

**Comment by LordTrav** [comment]
After further testing, untamed animals can be named, but tamed ones cannot. Also, if an animal is named, then tamed, it will lose it's name.

**Comment by LordTrav** [comment]
**Cannot be fixed**
I advise against using nametags on tamed pets for now.
