### ISSUE TITLE
Walking while dead (underwater) 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#45]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- go into a pool of water & drown
- press left shift 
- start walking, while dead

**What you expected would happen**

- I wouldn’t be able to move, cause i’m knocked out 

**What actually happened**

- I was able to move even while dead 

**Logs and screenshots**
- Sent on discord :D

**Comment by nnichael** [comment]
For now, this is intentional!
