### ISSUE TITLE
Getting paid for mob control and Medic/Cop

### ISSUE THREAD

**Issue by JollyTheDuck** [nnichael/MOGL#46]
**List your installed mods**

- fabric
- Xaero's Minimap
-Squeedometer
-Inventory HUD

**How you triggered the behavior**

- log into MOGL
- Obtain job for Medic/cop and Mob Control
- punched a druggie then applied a syringe to it

**What you expected would happen**

- Nothing

**What actually happened**

- I got Paid as a medic for curing Druggie(cop for taking out Druggie) and as mob control for taking it out

**Logs and screenshots**
![2021-11-10_12 22 07](https://user-images.githubusercontent.com/94073604/141171072-105aec9a-0377-4864-8237-e0546892f3bc.png)

**Comment by nnichael** [comment]
Making changes to get this fixed. Thanks!
