### ISSUE TITLE
leaderboards not updating

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#48]
**list your installed mods**

- none

**how you triggered the behavior**

- log into mogl
- look at leaderboards

**what you expected would happen**

- they'd look just like the /lb leaderboard

**what actually happened**

- they didn't change

**logs and screenshots**
<img width="446" alt="Screen Shot 2021-11-13 at 3 22 36 PM" src="https://user-images.githubusercontent.com/92835506/141661817-188b90aa-83dd-41f4-93c8-40b3f3fd4d10.png">
<img width="360" alt="Screen Shot 2021-11-13 at 3 22 48 PM" src="https://user-images.githubusercontent.com/92835506/141661820-b7346317-f683-4b17-bef2-5f13d0316bfd.png">

**Comment by nnichael** [comment]
@Pumpkin-Headington thought I already closed this one. Can you confirm it's broken, and not just really slow? Because I believe they're just really slow to update. 

Unless it's, for example, been an IRL 3 or 4 days and it's still not updated. Let me know, thanks!

**Comment by nnichael** [comment]
Going to close this for now. I believe they don't update if they aren't in a loaded chunk during the "update" time. Let me know if they never update... ever... I'll reopen it.
