### ISSUE TITLE
Car uses don’t decrease 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#54]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- get into my car 
- get out of it 
- get back in the car 
- noticed my uses didn’t go down at all

**What you expected would happen**

-i expected the number of uses to go down, but instead they remained the same 

**What actually happened**

- number of uses remained the same 

**Logs and screenshots**
- this screenshot is the number of uses BEFORE getting into my car 

![670F5999-1E07-47D9-824D-5704767B3708](https://user-images.githubusercontent.com/91354495/142372797-099db781-0c3b-4ba3-be5f-92ab7831127f.png)

- this screenshot is the number of uses AFTER using my car 

![A59D1401-5025-46A5-AA74-3A47FBFC5B08](https://user-images.githubusercontent.com/91354495/142372892-03645a88-2c04-46c2-b89b-f2efb2973013.png)

**Comment by nnichael** [comment]
There is a new way engines work. It no longer goes down just by getting in/out of your vehicle. @m0nts3
