### ISSUE TITLE
Property furniture

### ISSUE THREAD

**Issue by Wizard8284** [nnichael/MOGL#69]
**List your installed mods**

- optifine

**How you triggered the behavior**
- I bought a new property, which contained the remnants of other player belongings, this included a few pieces of VIP++ furniture, I tried to remove the furniture as I wanted to re-decorate the place.

**What you expected would happen**
-  The furniture would disappear 
- 
**What actually happened**
- furniture didn't disappear and the message that it gave me said "you do not own this furniture"

**Logs and screenshots**
- Yikes forgot about this

- Lethal helped me remove the furniture on the property in the end

**Comment by nnichael** [comment]
@Wizard8284 that message is only called when trying to rotate furniture & I cannot recreate this bug. I'm going to close this for now. Feel free to open a ticket or another issue if it happens again.
