### ISSUE TITLE
Recycle police vest 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#74]
**List your installed mods**
- optifine 

**How you triggered the behavior**

- log into MOGL
- go to recycle center and recycle my cop vest 

**What you expected would happen**

- wouldn’t be able to recycle it 

**What actually happened**

- it recycled and i’m a cop with no vest now 

**Logs and screenshots**
- let me know if you need a recording & i’ll remake it

**Comment by LordTrav** [comment]
Fixed on next restart.
