### ISSUE TITLE
mayor can not buy cop car

### ISSUE THREAD

**Issue by nightmare594** [nnichael/MOGL#77]
**List your installed mods**

- none

**How you triggered the behavior**
tried to buy cop car

**What you expected would happen**
to get the cop car

**What actually happened**
was told only mayor could buy a cop car even though is a mayor

**Logs and screenshots**

![2022-02-10_22 10 48](https://user-images.githubusercontent.com/99459408/153532793-dd1d047b-3fef-4148-87cf-5fd67984415e.png)

**Comment by PigleB605** [comment]
Note: May be a follow-up to #76
