### ISSUE TITLE
Plumber Boss Bar stuck on screen

### ISSUE THREAD

**Issue by xoLethalxo** [nnichael/MOGL#8]
**List your installed mods**

- optifine
- dramatic skies

**Call Plumber Bug**

-I needed to do a turd but i'd previously clogged my toilet.
- Called a Plumber
- Plumber recieved request
- Tracker didnt change 
- Emailed plumber to tell them where I was
- They came and unclogged the toilet
- They left
- The Plumber Tracker is still on my screen till I relogged

![2021-10-18_13 13 35](https://user-images.githubusercontent.com/73149538/137664536-ded59b33-4ed5-4bfe-bb3b-361135571e1c.png)

**Comment by nnichael** [comment]
This old bug, I THINK, has been fixed. Will reopen if it reoccurs.
