### ISSUE TITLE
Sink Bug 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#93]
**List your installed mods**

- optifine

**How you triggered the behavior**

wash hands 10+ times 
sink didnt break 

**What you expected would happen**

- the sink to break

**Comment by PigleB605** [comment]
Thanks for the report, @m0nts3! 

By any chance, is one of your jobs Plumber? Like with toilets, Plumbers do not add to a hygiene unit's uses. Let me know, and I'll take a closer look into it.

**Comment by PigleB605** [comment]
Tested it myself and there was indeed a bug; fixed for the next restart. Thanks for the report!

**Comment by nnichael** [comment]
The issue persists! D:
