### ISSUE TITLE
Medic cure druggie bug 

### ISSUE THREAD

**Issue by m0nts3** [nnichael/MOGL#94]
**List your installed mods**

- optifine

**How you triggered the behavior**

- log into MOGL
- Try to disinfect a druggie
- Does not let you disinfect for some reason

**Comment by nnichael** [comment]
Gonna close this one for now. Due to recent changes, all old mobs need to DIE, so the new ones can spawn in, then it should be working. Let me know if I should re-open this after some time has passed.
